MDScreenManager:
    Home

<Home>
    name: "Home"

    # StackLayout to arrange widgets vertically
    StackLayout:

        # MDTopAppBar with correct positioning
        MDTopAppBar:
            title: "Talk to Gemini"
            pos_hint: {"top": 1}  # Set top position at 1

        FloatLayout:
            MDLabel:
                id: ans
                text: ""
                pos_hint: {"center_x": .5, "center_y": .95}
            MDCard:
                pos_hint: {"center_x": .5, "center_y": .52}
                size_hint: .95, .5

                FloatLayout:
                    MDRoundFlatButton:
                        text: "Get anser"
                        pos_hint: {"x": .8, "y": .45}
                        on_release: root.get_gem()
                    MDTextField:
                        id: input
                        hint_text: "Talk to Gemini"
                        size_hint: None,None
                        width: 200
                        pos_hint: {"x": .1, "y": .4}
